[package]
name = "bevy_snake"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "^0.7.0"
fastrand = "^1.7.0"

[features]
default = ["dyn"]
dyn = ["bevy/dynamic"]
